### 예외처리가 필요한 이유

---

- **프로그램 실행 중에 발생하는** 에러를 미연에 방지

### try, except, else, finally

---

```python
try:
	예외가 발생할 수 있는 코드
except:
	예외 발생 시 실행할 코드 
else:
	예외 발생하지 않은 경우 실행할 코드
finally:
	항상 실행할 코드 
```

### try, except문

---

```python
try:
	...
except: [발생 오류[as 오류 메세지 변수]]:
	...
```

try 블록 수행 중 오류가 발생하면 except 블록이 수행된다. 하지만 try 블록에서 오류가 발생하지 않는 다면 except 블록은 수행되지 않는다. 

> except [발생 오류 [as 오류 메시지 변수]]:
> 

위 구문을 보면 [ ] 기호를 사용하는데, 이 기호는 괄호 안의 내용을 생략할 수 있다는 표기법이다. 

1. **try ,except만 쓰는 방법**
    
    ```python
    try:
    	...
    except:
    	...
    ```
    
    - 이 경우는 오류 종류에 상관없이 오류가 발생하면 except 블록을 수행한다.
2. **발생 오류만 포함한 except 문**
    
    ```python
    try:
    	...
    except 발생 오류:
    	...
    ```
    
    - 이 경우는 오류가 발생했을 때 except문에 미리 정해 놓은 오류 이름과 일치할 때만 except 블록을 수행한다.
3. **발생 오류와 오류 메시지 변수까지 포함한 except문**
    
    ```python
    try:
    	...
    except 발생 오류 as 오류 메시지 변수:
    	...
    ```
    
    - 이 경우는 두번째 경우에서 오류 메시지의 내용까지 알고 싶을 때 사용하는 방법이다.

### try .. finally

---

try 문에는 finally 절을 사용할 수 있다.  finally 절은 try 문 수행 도중 **예외 발생 여부에 상관없이** 수행된다. **보통 finally 절은 사용한 리소스를 close 해야 할 때에 많이 사용**한다.

```python
f = open('foo.txt','w')
try:
	...
finally:
	f.close()
```

### 여러개의 오류처리하기

---

```python
try:
    ...
except 발생 오류1:
   ... 
except 발생 오류2:
   ...
```

- 2개 이상의 오류를 동일하게 처리하기 위해서는 괄호를 사용하여 함께 묶어서 처리
    
    ```python
    try:
        a = [1,2]
        print(a[3])
        4/0
    except (ZeroDivisionError, IndexError) as e:
        print(e)
    ```
    

### try문에 else절 사용하기

---

```python
try:
    ...
except [발생 오류[as 오류 메시지 변수]]:
    ...
else:  # 오류가 없을 경우에만 수행된다.
    ...
```

try문 수행중 오류가 발생하면 except 절이 수행되고 오류가 없으면 else절이 수행된다.

```python
 try:
    age=int(input('나이를 입력하세요: '))
except:
    print('입력이 정확하지 않습니다.')
else:
    if age <= 18:
        print('미성년자는 출입금지입니다.')
    else:
        print('환영합니다.')
```